swagger: '2.0'
info:
  version: '1.0'
  title: Meu Câmbio - V1 API
  description: Documentação da API do teste para a empresa Meu Câmbio.
  contact: {}
host: localhost:8006
basePath: /api/v1
securityDefinitions:
  auth:
    type: oauth2
    flow: implicit
    authorizationUrl: http://localhost:8006/api/v1
    scopes: {}
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /auth/logout:
    post:
      description: Recurso responsável por fazer o logout na aplicação.
      summary: Logout
      tags:
      - Auth
      operationId: AuthLogoutPost
      produces:
      - application/json
      parameters:
      - name: Accept
        in: header
        required: true
        type: string
        description: ''
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
          headers: {}
      security:
      - auth: []
  /auth/login:
    post:
      description: Recurso responsável por fazer o login na aplicação.
      summary: Login
      tags:
      - Auth
      operationId: AuthLoginPost
      produces:
      - application/json
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - name: email
        in: formData
        required: true
        type: string
        description: ''
      - name: password
        in: formData
        required: true
        type: string
        description: ''
      - name: Accept
        in: header
        required: true
        type: string
        description: ''
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
          headers: {}
      security:
      - auth: []
  /auth/me:
    post:
      description: Recurso responsável por retornar as informações do próprio token/usuário (dono do token).
      summary: Me
      tags:
      - Auth
      operationId: AuthMePost
      produces:
      - application/json
      parameters:
      - name: Accept
        in: header
        required: true
        type: string
        description: ''
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
          headers: {}
      security:
      - auth: []
  /auth/refresh:
    post:
      description: Recurso responsável por fazer a atualização do token atual.
      summary: Refresh Token
      tags:
      - Auth
      operationId: AuthRefreshPost
      produces:
      - application/json
      parameters:
      - name: Accept
        in: header
        required: true
        type: string
        description: ''
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
          headers: {}
      security:
      - auth: []
  /news:
    get:
      description: Recurso responsável por listar as novidades do feed.
      summary: List
      tags:
      - Feed
      operationId: NewsGet
      produces:
      - application/json
      parameters:
      - name: page
        in: query
        required: true
        type: integer
        format: int32
        description: ''
      - name: per_page
        in: query
        required: true
        type: integer
        format: int32
        description: ''
      - name: filter
        in: query
        required: true
        type: string
        description: ''
      - name: Accept
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
          headers: {}
      security:
      - auth: []
  /news/1:
    get:
      description: Recurso responsável por exibir uma única publicação do feed.
      summary: Show
      tags:
      - Feed
      operationId: News1Get
      produces:
      - application/json
      parameters:
      - name: Accept
        in: header
        required: true
        type: string
        description: ''
      - name: Content-Type
        in: header
        required: true
        type: string
        description: ''
      responses:
        200:
          description: ''
          headers: {}
      security:
      - auth: []
tags:
- name: Auth
- name: Feed